src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Denomination;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $DCI;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Dosage;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Voie;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Laboratoire;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $idLaboratoire;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $TypeProcedure;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CodeCIS;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CodeVU;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CodeDossier;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $NomVU;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $Codex;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Titulaire;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $idTitulaire;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $AdresseContact;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $AdresseCompl;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CodePost;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $NomVille;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $TelContact;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $FaxContact;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Adresse;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $AdresseComplExpl;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CodePostExpl;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $NomVilleExpl;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Complement;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Tel;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Fax;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CodeATC;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $LibATC;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $DP;

    // #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[ORM\Column(type: 'text', nullable: true)]
    private $PrescriptionDelivrance;

    #[ORM\ManyToOne(targetEntity: SignalANSM::class, inversedBy: 'produits')]
    private $ProduitSignal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDenomination(): ?string
    {
        return $this->Denomination;
    }

    public function setDenomination(?string $Denomination): self
    {
        $this->Denomination = $Denomination;

        return $this;
    }

    public function getDCI(): ?string
    {
        return $this->DCI;
    }

    public function setDCI(?string $DCI): self
    {
        $this->DCI = $DCI;

        return $this;
    }

    public function getDosage(): ?string
    {
        return $this->Dosage;
    }

    public function setDosage(?string $Dosage): self
    {
        $this->Dosage = $Dosage;

        return $this;
    }

    public function getVoie(): ?string
    {
        return $this->Voie;
    }

    public function setVoie(?string $Voie): self
    {
        $this->Voie = $Voie;

        return $this;
    }

    public function getLaboratoire(): ?string
    {
        return $this->Laboratoire;
    }

    public function setLaboratoire(?string $Laboratoire): self
    {
        $this->Laboratoire = $Laboratoire;

        return $this;
    }

    public function getIdLaboratoire(): ?string
    {
        return $this->idLaboratoire;
    }

    public function setIdLaboratoire(?string $idLaboratoire): self
    {
        $this->idLaboratoire = $idLaboratoire;

        return $this;
    }

    public function getTypeProcedure(): ?string
    {
        return $this->TypeProcedure;
    }

    public function setTypeProcedure(?string $TypeProcedure): self
    {
        $this->TypeProcedure = $TypeProcedure;

        return $this;
    }

    public function getCodeCIS(): ?string
    {
        return $this->CodeCIS;
    }

    public function setCodeCIS(?string $CodeCIS): self
    {
        $this->CodeCIS = $CodeCIS;

        return $this;
    }

    public function getCodeVU(): ?string
    {
        return $this->CodeVU;
    }

    public function setCodeVU(?string $CodeVU): self
    {
        $this->CodeVU = $CodeVU;

        return $this;
    }

    public function getCodeDossier(): ?string
    {
        return $this->CodeDossier;
    }

    public function setCodeDossier(?string $CodeDossier): self
    {
        $this->CodeDossier = $CodeDossier;

        return $this;
    }

    public function getNomVU(): ?string
    {
        return $this->NomVU;
    }

    public function setNomVU(?string $NomVU): self
    {
        $this->NomVU = $NomVU;

        return $this;
    }

    public function getCodex(): ?bool
    {
        return $this->Codex;
    }

    public function setCodex(?bool $Codex): self
    {
        $this->Codex = $Codex;

        return $this;
    }

    public function getTitulaire(): ?string
    {
        return $this->Titulaire;
    }

    public function setTitulaire(?string $Titulaire): self
    {
        $this->Titulaire = $Titulaire;

        return $this;
    }

    public function getIdTitulaire(): ?string
    {
        return $this->idTitulaire;
    }

    public function setIdTitulaire(?string $idTitulaire): self
    {
        $this->idTitulaire = $idTitulaire;

        return $this;
    }

    public function getAdresseContact(): ?string
    {
        return $this->AdresseContact;
    }

    public function setAdresseContact(?string $AdresseContact): self
    {
        $this->AdresseContact = $AdresseContact;

        return $this;
    }

    public function getAdresseCompl(): ?string
    {
        return $this->AdresseCompl;
    }

    public function setAdresseCompl(?string $AdresseCompl): self
    {
        $this->AdresseCompl = $AdresseCompl;

        return $this;
    }

    public function getCodePost(): ?string
    {
        return $this->CodePost;
    }

    public function setCodePost(?string $CodePost): self
    {
        $this->CodePost = $CodePost;

        return $this;
    }

    public function getNomVille(): ?string
    {
        return $this->NomVille;
    }

    public function setNomVille(?string $NomVille): self
    {
        $this->NomVille = $NomVille;

        return $this;
    }

    public function getTelContact(): ?string
    {
        return $this->TelContact;
    }

    public function setTelContact(?string $TelContact): self
    {
        $this->TelContact = $TelContact;

        return $this;
    }

    public function getFaxContact(): ?string
    {
        return $this->FaxContact;
    }

    public function setFaxContact(?string $FaxContact): self
    {
        $this->FaxContact = $FaxContact;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(?string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getAdresseComplExpl(): ?string
    {
        return $this->AdresseComplExpl;
    }

    public function setAdresseComplExpl(?string $AdresseComplExpl): self
    {
        $this->AdresseComplExpl = $AdresseComplExpl;

        return $this;
    }

    public function getCodePostExpl(): ?string
    {
        return $this->CodePostExpl;
    }

    public function setCodePostExpl(?string $CodePostExpl): self
    {
        $this->CodePostExpl = $CodePostExpl;

        return $this;
    }

    public function getNomVilleExpl(): ?string
    {
        return $this->NomVilleExpl;
    }

    public function setNomVilleExpl(?string $NomVilleExpl): self
    {
        $this->NomVilleExpl = $NomVilleExpl;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->Complement;
    }

    public function setComplement(?string $Complement): self
    {
        $this->Complement = $Complement;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->Fax;
    }

    public function setFax(?string $Fax): self
    {
        $this->Fax = $Fax;

        return $this;
    }

    public function getCodeATC(): ?string
    {
        return $this->CodeATC;
    }

    public function setCodeATC(?string $CodeATC): self
    {
        $this->CodeATC = $CodeATC;

        return $this;
    }

    public function getLibATC(): ?string
    {
        return $this->LibATC;
    }

    public function setLibATC(?string $LibATC): self
    {
        $this->LibATC = $LibATC;

        return $this;
    }

    public function getDP(): ?string
    {
        return $this->DP;
    }

    public function setDP(?string $DP): self
    {
        $this->DP = $DP;

        return $this;
    }

    public function getPrescriptionDelivrance(): ?string
    {
        return $this->PrescriptionDelivrance;
    }

src/Controller/CreationProduitController.php
<?php

namespace App\Controller;

use App\Form\ProduitType;
use App\Entity\SignalANSM;
use App\Codex\RequetesCodex;
use App\Form\SearchCodexType;
use App\Entity\Codex\SearchCodex;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CreationProduitController extends AbstractController
{
    #[Route('/creation_produit/recherche/{idSignal}', name: 'app_creation_produit')]
    public function index(ManagerRegistry $doctrine, Request $request, PaginatorInterface $paginator,int $idSignal): Response
    {
        
        $search = new SearchCodex;
        $form = $this->createForm(SearchCodexType::class, $search);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('recherche')->isClicked()) {
                // si on a cliqué sur le bouton de recherche 
                $RqCodex = new RequetesCodex($doctrine);
                $ListeProduits = $RqCodex->donneProduit_SearchCodex($search);
                $NbProduits = count($ListeProduits);
            } else if ($form->get('reset')->isClicked()) {
                // si on a cliqué sur le bouton reset 
                $RqCodex = new RequetesCodex($doctrine);
                $ListeProduits = $RqCodex->donneProduit_SearchCodex($search);
                $NbProduits = count($ListeProduits);
            } else {
                dd('je sais pas quoi faire');
            }
            
        } elseif ($form->isSubmitted() && $form->isValid() == false) {
            // Si on a cliqué sur un des boutons du paginator (le formulaire est alors "isSubmitted()" mais pas "isValid()")
            $RqCodex = new RequetesCodex($doctrine);
            $ListeProduits = $RqCodex->donneProduit_SearchCodex($search);
            $NbProduits = count($ListeProduits);

        } else {
            // Affichage de tous les susars par defaut :
            $RqCodex = new RequetesCodex($doctrine);
            $ListeProduits = $RqCodex->donneProduit_SearchCodex($search);
            $NbProduits = count($ListeProduits);
        }
        $LstProduits = $paginator->paginate(
            $ListeProduits, 
            $request->query->getInt('page', 1),
            15
        );
            
        if (!isset($NbProduits)) {
            $NbProduits = 0;
        }
        if (!isset($LstProduits)) {
            $LstProduits = [];
        }
        
        return $this->render('creation_produit/recherche.html.twig', [
            'LstProduits' => $LstProduits,
            'form' => $form->createView(),
            'NbProduits' => $NbProduits,
            'idSignal' => $idSignal,
        ]);
    }

    #[Route('/creation_produit/saisie/{idSignal}/{codeVU}', name: 'app_creation_produit_saisie')]
    public function saisie(ManagerRegistry $doctrine, Request $request, PaginatorInterface $paginator, EntityManagerInterface $em, int $idSignal, int $codeVU): Response
    {

        $RqCodex = new RequetesCodex($doctrine);
        $produit = $RqCodex->donneProduit_parCodeVU($codeVU);
        $signal = $em->getRepository(SignalANSM::class)->findOneById($idSignal);
        $produit->setProduitSignal($signal);
        $form = $this->createForm(ProduitType::class, $produit);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $em->persist($produit);
            $em->flush();
            // return $this->redirectToRoute('affiche_signal'); 
            return $this->redirectToRoute('recherche_signal');
        }

        return $this->render('creation_produit/saisie.html.twig', [
            'form' => $form->createView(),
            'idSignal' => $idSignal,
            'codeVU' => $codeVU,
        ]);
    }


}

templates/creation_produit/recherche.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherche / Création de produit - recherche de produits{% endblock %}

{% block body %}

<div class="container-fluid p-5">
	{{form_start(form)}}
		<div class="row">
			<div class="col-3">
				{{ form_label(form.denomination, 'Dénomination :') }}
				{{ form_widget(form.denomination) }}
			</div>
			<div class="col-3">
				{{ form_label(form.dci, 'DCI :') }}
				{{ form_widget(form.dci) }}
			</div>
		</div>
	    <div class="row">
			<div class="col-1">
				{{ form_label(form.recherche, 'Recherche') }}
				{{ form_widget(form.recherche) }}
			</div>
			<div class="col-1">
				{{ form_label(form.reset, 'Reset') }}
				{{ form_widget(form.reset) }}
			</div>
		</div>
	{{form_end(form)}}

	</div>
		<div class="container-fluid">
			{% if LstProduits %}
				Nombre de lignes : {{ NbProduits }}
				{# <h3>Liste des Produits : </h3> #}
				{# {{dump(Susars)}} #}
				<table class="table table-sm table-bordered table-hover text-center">
					<thead class="table-secondary">
						<tr>
							<th scope="col">création du produit</th>
							{# <th scope="col">codeVU</th>
							<th scope="col">codeDossier</th> #}
							<th scope="col-2">Dénomination</th>
							<th scope="col-2">DCI</th>
							<th scope="col">Dosage</th>
							<th scope="col">Voie</th>
						</tr>
					</thead>
					<tbody>
						{% for Produit in LstProduits %}
							<tr>
								<td> 
								<a class="btn btn-primary" href="{{ path('app_creation_produit_saisie',{'idSignal': idSignal,'codeVU':Produit.codeVU}) }}" role="button">Aj. prod. ({{ Produit.codeVU|e }})</a>
								
								{# <button type="button" ></button>  #}
								
								 {# {{ Produit.codeVU|e }} #}
								
								
									{# <a href="{{ path('app_affiche_susar',{'master_id':cas.MasterId}) }}">{{ cas.specificcaseid|e }}</a> #}
								
								</td>
								{# <td>{{ Produit.codeVU|e }}</td>
								<td>{{ Produit.codeDossier|e }}</td> #}
								<td>{{ Produit.nomVU|e }}</td>
								<td>{{ Produit.nomSubstance|e }}</td>
								<td>{{ Produit.dosageLibra|e }}</td>
								<td>{{ Produit.libCourt|e }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				{{ knp_pagination_render(LstProduits) }}
			{% endif %}
		</div>
{% endblock %}

templates/creation_produit/saisie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherche / Création de produit - saisie de médicament{% endblock %}

{% block body %}

<div class="container-fluid mx-5 my-2">
{# <div class="container"> #}

	{# {{idSignal}}
	<br>
	{{codeVU}} #}


	{{form_start(form)}}

		<div class="row">
			<div class="col-12">
				{{ form_label(form.Denomination, 'Dénomination :') }}
				{{ form_widget(form.Denomination) }}
			</div>
		</div>
		<div class="row">
			<div class="col-10">
				{{ form_label(form.DCI, 'DCI :') }}
				{{ form_widget(form.DCI) }}
			</div>
			<div class="col-2">
				{{ form_label(form.CodeDossier, 'Code dossier :') }}
				{{ form_widget(form.CodeDossier) }}
			</div>
		</div>

		<div class="row">
			<div class="col-2">
				{{ form_label(form.CodeATC, 'Code ATC :') }}
				{{ form_widget(form.CodeATC) }}
			</div>
			<div class="col-8">
				{{ form_label(form.LibATC, 'Libellé ATC :') }}
				{{ form_widget(form.LibATC) }}
			</div>
			<div class="col-2">
				{{ form_label(form.CodeCIS, 'Code CIS :') }}
				{{ form_widget(form.CodeCIS) }}
			</div>
		</div>

		<div class="row">
			<div class="col-2">
				{{ form_label(form.Voie, 'Voie :') }}
				{{ form_widget(form.Voie) }}
			</div>
			<div class="col-8">
				{{ form_label(form.Dosage, 'Dosage :') }}
				{{ form_widget(form.Dosage) }}
			</div>
			<div class="col-2">
				{{ form_label(form.TypeProcedure, 'Type procédure :') }}
				{{ form_widget(form.TypeProcedure) }}
			</div>
		</div>

		<div class="row">
			<div class="col-12">
				{{ form_label(form.PrescriptionDelivrance, 'Conditions de prescription et de délivrance :') }}
				{{ form_widget(form.PrescriptionDelivrance) }}
			</div>
		</div>

		<div class="row">
			<div class="col-1">
				<b>Exploitant</b>
			</div>
			<div class="col-8">
				{{ form_label(form.Laboratoire, 'Laboratoire :') }}
				{{ form_widget(form.Laboratoire) }}
			</div>
			<div class="col-3">

			</div>
		</div>

		<div class="row">
			<div class="col-1">
				
			</div>
			<div class="col-9">
				{{ form_label(form.Adresse, 'Adresse :') }}
				{{ form_widget(form.Adresse) }}
			</div>
			<div class="col-2">
				{{ form_label(form.Tel, 'Téléphone :') }}
				{{ form_widget(form.Tel) }}
			</div>
		</div>
		<div class="row">
			<div class="col-1">
				
			</div>
			<div class="col-9">
				{{ form_label(form.AdresseComplExpl, 'Compl. adr. :') }}
				{{ form_widget(form.AdresseComplExpl) }}
			</div>
			<div class="col-2">
				{{ form_label(form.Fax, 'Fax :') }}
				{{ form_widget(form.Fax) }}
			</div>
		</div>
		<div class="row">
			<div class="col-1">
				
			</div>
			<div class="col-2">
				{{ form_label(form.CodePostExpl, 'Code postal :') }}
				{{ form_widget(form.CodePostExpl) }}
			</div>
			<div class="col-7">
				{{ form_label(form.NomVilleExpl, 'Ville :') }}
				{{ form_widget(form.NomVilleExpl) }}
			</div>
			<div class="col-2">

			</div>
		</div>


		<div class="row">
			<div class="col-1">
				<b>Titulaire</b>
			</div>
			<div class="col-8">
				{{ form_label(form.Titulaire, 'Laboratoire :') }}
				{{ form_widget(form.Titulaire) }}
			</div>
			<div class="col-3">

			</div>
		</div>

		<div class="row">
			<div class="col-1">
				
			</div>
			<div class="col-9">
				{{ form_label(form.AdresseContact, 'Adresse :') }}
				{{ form_widget(form.AdresseContact) }}
			</div>
			<div class="col-2">
				{{ form_label(form.TelContact, 'Téléphone :') }}
				{{ form_widget(form.TelContact) }}
			</div>
		</div>
		<div class="row">
			<div class="col-1">
				
			</div>
			<div class="col-9">
				{{ form_label(form.AdresseCompl, 'Compl. adr. :') }}
				{{ form_widget(form.AdresseCompl) }}
			</div>
			<div class="col-2">
				{{ form_label(form.FaxContact, 'Fax :') }}
				{{ form_widget(form.FaxContact) }}
			</div>
		</div>
		<div class="row">
			<div class="col-1">
				
			</div>
			<div class="col-2">
				{{ form_label(form.CodePost, 'Code postal :') }}
				{{ form_widget(form.CodePost) }}
			</div>
			<div class="col-7">
				{{ form_label(form.NomVille, 'Ville :') }}
				{{ form_widget(form.NomVille) }}
			</div>
			<div class="col-2">

			</div>
		</div>



	{# {{ form_widget(form._token) }} #}
	{{form_end(form)}}

	</div>
		
{% endblock %}