src/Entity/Signal.php
<?php

namespace App\Entity;

use App\Repository\SignalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: 'signal')]
#[ORM\Entity(repositoryClass: SignalRepository::class)]
class Signal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    private $DateCreation;

    #[ORM\Column(type: 'text', nullable: true)]
    private $Description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Indication;

    #[ORM\Column(type: 'text', nullable: true)]
    private $Contexte;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $NiveauRisqueInitial;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $NiveauRisqueFinal;

    #[ORM\Column(type: 'text', nullable: true)]
    private $AnaRisqueComment;

    #[ORM\Column(type: 'text', nullable: true)]
    private $ProposReducRisque;

    #[ORM\ManyToOne(targetEntity: SourceSignal::class, inversedBy: 'signals')]
    private $SourceSignal;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $RefSignal;

    #[ORM\ManyToOne(targetEntity: PoleDS::class, inversedBy: 'signals')]
    private $PoleDS;

    #[ORM\ManyToOne(targetEntity: DMM::class, inversedBy: 'signals')]
    private $DMM;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $IdentifiantSource;

    #[ORM\ManyToOne(targetEntity: PiloteDS::class, inversedBy: 'signals')]
    private $PiloteDS;

    #[ORM\ManyToOne(targetEntity: CoPiloteDS::class, inversedBy: 'signals')]
    private $CoPiloteDS;

    #[ORM\ManyToOne(targetEntity: StatutSignal::class, inversedBy: 'signals')]
    private $StatutSignal;

    #[ORM\ManyToOne(targetEntity: StatutEmetteur::class, inversedBy: 'signals')]
    private $StatutEmetteur;

    /**
     * @var Collection<int, Suivi>
     */
    // #[ORM\OneToMany(targetEntity: Suivi::class, mappedBy: 'SuiviSignal')]
    #[ORM\OneToMany(targetEntity: Suivi::class, mappedBy: 'SuiviSignal', cascade: ['persist'])]
    // #[ORM\OneToMany(targetEntity: Bar::class, mappedBy: 'foo', orphanRemoval: true, cascade: ['persist'])]
   // #[ORM\OneToMany(targetEntity: Suivi::class, mappedBy: 'SuiviSignal', cascade: 'persist')]
    // private $suivis;
    private Collection $suivis;

    // #[ORM\OneToMany(targetEntity: ReleveDecision::class, mappedBy: 'ReleveDecisionSignal')]
    // private $releveDecisions;

    #[ORM\OneToMany(targetEntity: Produit::class, mappedBy: 'ProduitSignal')]
    private $produits;

    public function __construct()
    {
        $this->suivis = new ArrayCollection();
        $this->releveDecisions = new ArrayCollection();
        $this->produits = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getIndication(): ?string
    {
        return $this->Indication;
    }

    public function setIndication(?string $Indication): self
    {
        $this->Indication = $Indication;

        return $this;
    }

    public function getContexte(): ?string
    {
        return $this->Contexte;
    }

    public function setContexte(?string $Contexte): self
    {
        $this->Contexte = $Contexte;

        return $this;
    }

    public function getNiveauRisqueInitial(): ?string
    {
        return $this->NiveauRisqueInitial;
    }

    public function setNiveauRisqueInitial(?string $NiveauRisqueInitial): self
    {
        $this->NiveauRisqueInitial = $NiveauRisqueInitial;

        return $this;
    }

    public function getNiveauRisqueFinal(): ?string
    {
        return $this->NiveauRisqueFinal;
    }

    public function setNiveauRisqueFinal(?string $NiveauRisqueFinal): self
    {
        $this->NiveauRisqueFinal = $NiveauRisqueFinal;

        return $this;
    }

    public function getAnaRisqueComment(): ?string
    {
        return $this->AnaRisqueComment;
    }

    public function setAnaRisqueComment(?string $AnaRisqueComment): self
    {
        $this->AnaRisqueComment = $AnaRisqueComment;

        return $this;
    }

    public function getProposReducRisque(): ?string
    {
        return $this->ProposReducRisque;
    }

    public function setProposReducRisque(?string $ProposReducRisque): self
    {
        $this->ProposReducRisque = $ProposReducRisque;

        return $this;
    }

    public function getSourceSignal(): ?SourceSignal
    {
        return $this->SourceSignal;
    }

    public function setSourceSignal(?SourceSignal $SourceSignal): self
    {
        $this->SourceSignal = $SourceSignal;

        return $this;
    }

    public function getRefSignal(): ?string
    {
        return $this->RefSignal;
    }

    public function setRefSignal(?string $RefSignal): self
    {
        $this->RefSignal = $RefSignal;

        return $this;
    }

    public function getPoleDS(): ?PoleDS
    {
        return $this->PoleDS;
    }

    public function setPoleDS(?PoleDS $PoleDS): self
    {
        $this->PoleDS = $PoleDS;

        return $this;
    }

    public function getDMM(): ?DMM
    {
        return $this->DMM;
    }

    public function setDMM(?DMM $DMM): self
    {
        $this->DMM = $DMM;

        return $this;
    }

    public function getIdentifiantSource(): ?string
    {
        return $this->IdentifiantSource;
    }

    public function setIdentifiantSource(?string $IdentifiantSource): self
    {
        $this->IdentifiantSource = $IdentifiantSource;

        return $this;
    }

    public function getPiloteDS(): ?PiloteDS
    {
        return $this->PiloteDS;
    }

    public function setPiloteDS(?PiloteDS $PiloteDS): self
    {
        $this->PiloteDS = $PiloteDS;

        return $this;
    }

    public function getCoPiloteDS(): ?CoPiloteDS
    {
        return $this->CoPiloteDS;
    }

    public function setCoPiloteDS(?CoPiloteDS $CoPiloteDS): self
    {
        $this->CoPiloteDS = $CoPiloteDS;

        return $this;
    }

    public function getStatutSignal(): ?StatutSignal
    {
        return $this->StatutSignal;
    }

    public function setStatutSignal(?StatutSignal $StatutSignal): self
    {
        $this->StatutSignal = $StatutSignal;

        return $this;
    }

    public function getStatutEmetteur(): ?StatutEmetteur
    {
        return $this->StatutEmetteur;
    }

    public function setStatutEmetteur(?StatutEmetteur $StatutEmetteur): self
    {
        $this->StatutEmetteur = $StatutEmetteur;

        return $this;
    }

    /**
     * @return Collection|Suivi[]
     */
    public function getSuivis(): Collection
    {
        return $this->suivis;
    }

    public function addSuivi(Suivi $suivi): self
    {
        if (!$this->suivis->contains($suivi)) {
            $this->suivis->add($suivi);
            // $this->suivis[] = $suivi;
            $suivi->setSuiviSignal($this);
        }

        return $this;
    }

    public function removeSuivi(Suivi $suivi): self
    {
        if ($this->suivis->removeElement($suivi)) {
            // set the owning side to null (unless already changed)
            if ($suivi->getSuiviSignal() === $this) {
                $suivi->setSuiviSignal(null);
            }
        }

        return $this;
    }

    // /**
    //  * @return Collection|ReleveDecision[]
    //  */
    // public function getReleveDecisions(): Collection
    // {
    //     return $this->releveDecisions;
    // }

    // public function addReleveDecision(ReleveDecision $releveDecision): self
    // {
    //     if (!$this->releveDecisions->contains($releveDecision)) {
    //         $this->releveDecisions[] = $releveDecision;
    //         $releveDecision->setReleveDecisionSignal($this);
    //     }

    //     return $this;
    // }

    // public function removeReleveDecision(ReleveDecision $releveDecision): self
    // {
    //     if ($this->releveDecisions->removeElement($releveDecision)) {
    //         // set the owning side to null (unless already changed)
    //         if ($releveDecision->getReleveDecisionSignal() === $this) {
    //             $releveDecision->setReleveDecisionSignal(null);
    //         }
    //     }

    //     return $this;
    // }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setProduitSignal($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getProduitSignal() === $this) {
                $produit->setProduitSignal(null);
            }
        }

        return $this;
    }


}

src/Entity/Suivi.php
<?php

namespace App\Entity;

use App\Repository\SuiviRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SuiviRepository::class)]
class Suivi
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $DateSuivi;

    #[ORM\Column(type: 'text', nullable: true)]
    private $Description;

    #[ORM\ManyToOne(targetEntity: EmetteurSuivi::class, inversedBy: 'suivis')]
    private $EmetteurSuivi;

    #[ORM\ManyToOne(targetEntity: SignalANSM::class, inversedBy: 'suivis')]
    // #[ORM\ManyToOne(targetEntity: Foo::class, inversedBy: 'bars')]
    private $SuiviSignal;

    #[ORM\OneToMany(mappedBy: 'Suivi', targetEntity: ReleveDecision::class)]
    private Collection $releveDecisions;

    public function __construct()
    {
        $this->releveDecisions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateSuivi(): ?\DateTimeInterface
    {
        return $this->DateSuivi;
    }

    public function setDateSuivi(?\DateTimeInterface $DateSuivi): self
    {
        $this->DateSuivi = $DateSuivi;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getEmetteurSuivi(): ?EmetteurSuivi
    {
        return $this->EmetteurSuivi;
    }

    public function setEmetteurSuivi(?EmetteurSuivi $EmetteurSuivi): self
    {
        $this->EmetteurSuivi = $EmetteurSuivi;

        return $this;
    }

    public function getSuiviSignal(): ?SignalANSM
    {
        return $this->SuiviSignal;
    }

    public function setSuiviSignal(?SignalANSM $SuiviSignal): self
    {
        $this->SuiviSignal = $SuiviSignal;

        return $this;
    }

    /**
     * @return Collection<int, ReleveDecision>
     */
    public function getReleveDecisions(): Collection
    {
        return $this->releveDecisions;
    }

    public function addReleveDecision(ReleveDecision $releveDecision): self
    {
        if (!$this->releveDecisions->contains($releveDecision)) {
            $this->releveDecisions->add($releveDecision);
            $releveDecision->setSuivi($this);
        }

        return $this;
    }

    public function removeReleveDecision(ReleveDecision $releveDecision): self
    {
        if ($this->releveDecisions->removeElement($releveDecision)) {
            // set the owning side to null (unless already changed)
            if ($releveDecision->getSuivi() === $this) {
                $releveDecision->setSuivi(null);
            }
        }

        return $this;
    }
}

src/Controller/AfficheSignalController.php
<?php

namespace App\Controller;

use App\Form\SeekType;
use App\Entity\SignalANSM;
use App\Entity\Main\Signal;
use App\Form\NouvSignalDescSignalType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AfficheSignalController extends AbstractController
{
    #[Route(path: '/affiche_signal/{idSignal}', name: 'affiche_signal')]
    public function index(Request $request, ManagerRegistry $doctrine,EntityManagerInterface $em, int $idSignal): Response
    {
        
        $signal = $em->getRepository(SignalANSM::class)->findOneById($idSignal);
        $signalDescForm = $this->createForm(NouvSignalDescSignalType::class, $signal);
        $signalDescForm->handleRequest($request);
        // return $this->render('affiche_signal/index.html.twig', [
        //     'signals' => $signals,
        //     'controller_name' => 'AfficheSignalController',
        // ]);
        return $this->render('affiche_signal/affiche_signal.html.twig', [
            'signal' => $signal,
            'signal_desc_form' => $signalDescForm->createView(),
        ]);
    }
}

templates/affiche_signal/affiche_signal.html.twig
{% extends 'base.html.twig' %}

{% block title %}RéuSi - Recherche d'un signal{% endblock %}

{% block body %}

{{ encore_entry_link_tags('ReuSi_Header_CreaSignal') }}

<div class="container-header">

  <a href="{{ path('app_nouv_signal_desc_signal') }}"  class="btn-header-CreaSignal-actif" id="btn-1">Description du signal</a>
  <a href="{{ path('app_nouv_signal_suivi_signal') }}" class="btn-header-CreaSignal-inactif" id="btn-2">Suivi du signal</a>
  <a href="{{ path('app_nouv_signal_list_action') }}" class="btn-header-CreaSignal-inactif" id="btn-3">Liste des actions/mesures</a>

</div>  

{# {{ form(form) }} #}

<div id="onglet_1" class="onglet-aff">
  {# {% include 'nouveau_signal/nouv_signal_desc_signal.html.twig' %} #}

		<div class="container-fluid">



			{# {% if signal %}
        <table class="table table-dark table-hover">
                {{signal.id}} 
                {{signal.description}} <br>
                
                {% if signal.produits %}

                    {% for produit in signal.produits %}

                
                    &nbsp;&nbsp;&nbsp;
                    {{produit.denomination}} - {{produit.dci}}  <br>

                    {% endfor %}

                {% endif %}
        </table>


			{% endif %}
		</div> #}



Onglet description
<div class="container-fluid p-5">
    {# {{ form(signal_desc_form) }} #}
    {{form_start(signal_desc_form)}}

    <div class="row">
    <div class="col-2">
      IdSignal : {{signal.id}}
    </div>
      <div class="col-2">
        {{form_row(signal_desc_form.dateCreation)}}
      </div>
      <div class="col-8"></div>
    </div>


    <div class="row">
      <div class="col-12">
        {{form_row(signal_desc_form.description)}}
      </div>
    </div>


    <div class="row">
      <div class="col-12">
        Médicaments : <BR>
        {% if signal.produits|length > 0 %}
          <table class="table table-secondary table-hover table-striped table-bordered table-sm"> 
            <thead>
              <tr>
              <th scope="col" class="text-center h6">Modif/détail méd.</th>
              <th scope="col" class="text-center h5">Dénomination</th>
              <th scope="col" class="text-center h5">DCI</th>
              <th scope="col" class="text-center h5">Code ATC</th>
              <th scope="col" class="text-center h5">Voie</th>
              <th scope="col" class="text-center h5">Dosage</th>
              <th scope="col" class="text-center h5">Proc</th>
              </tr>
            </thead>
            <tbody>
              {% for produit in signal.produits %}
                <tr>
                    <th scope="row" class="text-center h6">
                        <a href="{{ path('affiche_produit',{'idProduit':produit.id}) }}" class="text-light">{{ produit.id|e }}</a>
                    </th>
                    <td class="h6">{{produit.Denomination|e}}</td>
                    <td class="h6">{{produit.DCI|e}}</td>
                    <td class="h6">{{produit.CodeATC|e}}</td>
                    <td class="h6">{{produit.Voie|e}}</td>
                    <td class="h6">{{produit.Dosage|e}}</td>
                    <td class="h6">{{produit.TypeProcedure|e}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          Pas de médicaments associé à ce signal
        {% endif %}

      </div>
      <div class="col-1">
				{{ form_widget(signal_desc_form.AjoutProduit) }}
      </div>
    </div>


    <div class="row">
      <div class="col-4">
        {{form_row(signal_desc_form.indication)}}
      </div>
      <div class="col-2">
        {{form_row(signal_desc_form.niveauRisqueInitial)}}
      </div>
      <div class="col-2">
        {{form_row(signal_desc_form.niveauRisqueFinal)}}
      </div>
      <div class="col-4">
        {{form_row(signal_desc_form.anaRisqueComment)}}
      </div>
    </div>


    <div class="row">
      <div class="col-6">
        {{form_row(signal_desc_form.contexte)}}
      </div>
      <div class="col-2">
        {{form_row(signal_desc_form.PiloteDS)}}
      </div>
      <div class="col-2">
        {{form_row(signal_desc_form.CoPiloteDS)}}
      </div>
    </div>


    <div class="row">
      <div class="col-3">
        {{form_row(signal_desc_form.sourceSignal)}}
      </div>
      <div class="col-3">
        {{form_row(signal_desc_form.refSignal)}}
      </div>
      <div class="col-3">
        {{form_row(signal_desc_form.poleDS)}}
      </div>
      <div class="col-3">
        {{form_row(signal_desc_form.dmm)}}
      </div>
    </div>


    <div class="row">
      <div class="col-4">
        {{form_row(signal_desc_form.identifiantSource)}}
      </div>
      <div class="col-4">
        {{form_row(signal_desc_form.statutEmetteur)}}
      </div>
      <div class="col-4">
        {{form_row(signal_desc_form.statutSignal)}}
      </div>
    </div>





      {# {{form_widget(signal_desc_form._token)}} #}

      {# <button type="button" class="btn btn-primary btn-new" data-collection="#suivis">Ajout suivi</button> #}
      <button type="button" class="btn-envoi m-2 btn-new" data-collection="#suivis">Ajout suivi</button>
      <div 
          id="suivis" 
          data-prototype="{{ include ('nouveau_signal/_suivi.html.twig', {form: signal_desc_form.suivis.vars.prototype})|e("html_attr") }}" 
          data-index="{{signal_desc_form.suivis|length > 0 ? signal_desc_form.suivis|last.vars.name + 1 : 0 }}">
        {% for suivi in signal_desc_form.suivis %}
          {{ include ('nouveau_signal/_suivi.html.twig', {form: suivi}) }}
        {% endfor %} 
      </div>

      
      {# {{form_row(signal_desc_form.submit)}} #}
    {{form_end(signal_desc_form,{render_rest: true}) }}
</div>



</div>

<div id="onglet_2" class="onglet-mask">
  {% include 'nouveau_signal/nouv_signal_suivi_signal.html.twig' %}
</div>

<div id="onglet_3" class="onglet-mask">
  {% include 'nouveau_signal/nouv_signal_mesure_signal.html.twig' %}
</div>
    
  
{% endblock %}


{% block javascripts %}
  {{ encore_entry_script_tags('ReuSi_Header_CreaSignal_js') }}
  {{ encore_entry_script_tags('ReuSi_ajoutSuivi_js') }}
{% endblock %}